#These are QA environment details
URL=https://www.americanairlines.in/intl/in/index.jsp
UserID=Tj@567
Pass=1234


#These are dev environment details
#URL=https://www.americanairlines.in/intl/in/index.jsp
#UID=hjk@899
#Pass=79808